global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ptk-microservices"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "ptk-service-auth:3000" # C'était 'auth-service' avant (FAUX)
          - "ptk-service-clients:3000" # C'était 'client-service' avant (FAUX)
          - "ptk-service-products:3000" # C'était 'product-service' avant (FAUX)
          - "ptk-service-orders:3000" # C'était 'order-service' avant (FAUX)

  - job_name: "rabbitmq"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ptk-rabbitmq:15692"]
