global:
  scrape_interval: 5s # On aspire les donn√©es toutes les 5 secondes

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000'] # Nom du service Docker : Port interne

  - job_name: 'client-service'
    static_configs:
      - targets: ['client-service:3000']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3000']